In [2]:
import sys
sys.executable


'c:\\Users\\alec.dewell\\jupyter\\.venv\\Scripts\\python.exe'

In [3]:
import numpy as np

arr2d = np.array([[1,2,3,4],[20,54,75,62],[45,89,100,120]])

arr2d 

array([[  1,   2,   3,   4],
       [ 20,  54,  75,  62],
       [ 45,  89, 100, 120]])

In [4]:
arr2d[2:,0:2]


array([[45, 89]])

In [5]:
arr2d[arr2d % 2 == 0]



array([  2,   4,  20,  54,  62, 100, 120])

In [6]:
arr_2d_prac = np.arange(50).reshape(10,5)
arr_2d_prac

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
arr_2d_prac[6:8,0:3]

array([[30, 31, 32],
       [35, 36, 37]])

In [8]:
import pandas as pd
from numpy.random import randn

np.random.seed(101)

In [9]:
df = pd.DataFrame(randn(5,4),['A', 'B', 'C', 'D', 'E'],['W', 'X', 'Y', 'Z'])
df

,W,X,Y,Z
A,2.706850,0.628133,0.907969,0.503826
B,0.651118,-0.319318,-0.848077,0.605965
C,-2.018168,0.740122,0.528813,-0.589001
D,0.188695,-0.758872,-0.933237,0.955057
E,0.190794,1.978757,2.605967,0.683509


In [10]:
print(df['W'])
type(df['W'])

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64


pandas.core.series.Series

In [11]:
df[df['W'] > 0][df['Y'] >1]
#can use & instead of multiple brackets as it is bitwise
df[(df['W'] > 0) & (df['Y'] > 1)]
#for or use |
df[(df['W'] > 0) | (df['Y'] > 1)]

C:\Users\alec.dewell\AppData\Local\Temp\ipykernel_35712\1658537725.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['W'] > 0][df['Y'] >1]


,W,X,Y,Z
A,2.706850,0.628133,0.907969,0.503826
B,0.651118,-0.319318,-0.848077,0.605965
D,0.188695,-0.758872,-0.933237,0.955057
E,0.190794,1.978757,2.605967,0.683509


In [12]:
df

,W,X,Y,Z
A,2.706850,0.628133,0.907969,0.503826
B,0.651118,-0.319318,-0.848077,0.605965
C,-2.018168,0.740122,0.528813,-0.589001
D,0.188695,-0.758872,-0.933237,0.955057
E,0.190794,1.978757,2.605967,0.683509


In [13]:
states = ['CA', 'NY', 'TX', 'FL', 'IL']
df['States'] = states
df

,W,X,Y,Z,States
A,2.706850,0.628133,0.907969,0.503826,CA
B,0.651118,-0.319318,-0.848077,0.605965,NY
C,-2.018168,0.740122,0.528813,-0.589001,TX
D,0.188695,-0.758872,-0.933237,0.955057,FL
E,0.190794,1.978757,2.605967,0.683509,IL


In [14]:
df.set_index('States', inplace=True)
#inplace means it will modify the original dataframe without needing to reassign it
df

,W,X,Y,Z
States,,,,
CA,2.706850,0.628133,0.907969,0.503826
NY,0.651118,-0.319318,-0.848077,0.605965
TX,-2.018168,0.740122,0.528813,-0.589001
FL,0.188695,-0.758872,-0.933237,0.955057
IL,0.190794,1.978757,2.605967,0.683509
