In [1]:
import sys
sys.executable


'd:\\Python Projects\\Jupyter\\Udemy_Course\\.venv\\Scripts\\python.exe'

In [9]:
import numpy as np

arr2d = np.array([[1,2,3,4],[20,54,75,62],[45,89,100,120]])

arr2d 

array([[  1,   2,   3,   4],
       [ 20,  54,  75,  62],
       [ 45,  89, 100, 120]])

In [11]:
arr2d[2:,0:2]


array([[45, 89]])

In [13]:
arr2d[arr2d % 2 == 0]



array([  2,   4,  20,  54,  62, 100, 120])

In [15]:
arr_2d_prac = np.arange(50).reshape(10,5)
arr_2d_prac

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
arr_2d_prac[6:8,0:3]

array([[30, 31, 32],
       [35, 36, 37]])

: 